### ISSUE TITLE
NullReferenceException in RedminePublisher

### ISSUE THREAD

**Issue by Seungmuk92** [TheFatDuck/NotionPublisher#1]
NotionPublisher Error
2023-05-16 16:43:51 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
2023-05-16 16:43:51       BackgroundService failed
2023-05-16 16:43:51       System.NullReferenceException: Object reference not set to an instance of an object.
2023-05-16 16:43:51          at RedminePublisher.IssuePublisher.PublishIssues() in /src/RedminePublisher/IssuePublisher.cs:line 48
2023-05-16 16:43:51          at RedminePublisher.IssuePublisher.ExecuteAsync(CancellationToken stoppingToken) in /src/RedminePublisher/IssuePublisher.cs:line 37
2023-05-16 16:43:51          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-05-16 16:43:51 crit: Microsoft.Extensions.Hosting.Internal.Host[10]
2023-05-16 16:43:51       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
2023-05-16 16:43:51       System.NullReferenceException: Object reference not set to an instance of an object.
2023-05-16 16:43:51          at RedminePublisher.IssuePublisher.PublishIssues() in /src/RedminePublisher/IssuePublisher.cs:line 48
2023-05-16 16:43:51          at RedminePublisher.IssuePublisher.ExecuteAsync(CancellationToken stoppingToken) in /src/RedminePublisher/IssuePublisher.cs:line 37
2023-05-16 16:43:51          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-05-16 16:43:51 info: Microsoft.Hosting.Lifetime[0]
2023-05-16 16:43:51       Application is shutting down...

**Comment by Seungmuk92** [comment]
The issue is closed as the same phenomenon does not recur.

**Comment by Seungmuk92** [comment]
동일 증상 반복으로 이슈 재 오픈

2023-08-28 07:58:19 | fail: Microsoft.Extensions.Hosting.Internal.Host[9]
2023-08-28 07:58:19 |       BackgroundService failed
2023-08-28 07:58:19 |       System.NullReferenceException: Object reference not set to an instance of an object.
2023-08-28 07:58:19 |          at RedmineWorker.Models.RedmineIssue.ConvertToDao() in /src/RedmineLoader/Models/RedmineIssue.cs:line 52
2023-08-28 07:58:19 |          at RedmineLoader.IssueLoader.PutIssues(List`1 issues) in /src/RedmineLoader/IssueLoader.cs:line 218
2023-08-28 07:58:19 |          at RedmineLoader.IssueLoader.ExecuteAsync(CancellationToken stoppingToken) in /src/RedmineLoader/IssueLoader.cs:line 53
2023-08-28 07:58:19 |          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-08-28 07:58:19 | crit: Microsoft.Extensions.Hosting.Internal.Host[10]
2023-08-28 07:58:19 |       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
2023-08-28 07:58:19 |       System.NullReferenceException: Object reference not set to an instance of an object.
2023-08-28 07:58:19 |          at RedmineWorker.Models.RedmineIssue.ConvertToDao() in /src/RedmineLoader/Models/RedmineIssue.cs:line 52
2023-08-28 07:58:19 |          at RedmineLoader.IssueLoader.PutIssues(List`1 issues) in /src/RedmineLoader/IssueLoader.cs:line 218
2023-08-28 07:58:19 |          at RedmineLoader.IssueLoader.ExecuteAsync(CancellationToken stoppingToken) in /src/RedmineLoader/IssueLoader.cs:line 53
2023-08-28 07:58:19 |          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-08-28 07:58:19 | info: Microsoft.Hosting.Lifetime[0]
